pub mod language_code {
    #[derive(Debug)]
    pub enum LanguageCode {
        Afrikaans,
        Albanian,
        Arabic,
        Azerbaijani,
        Bengali,
        Bulgarian,
        Catalan,
        ChineseChina,
        ChineseHongKong,
        ChineseTaiwan,
        Croatian,
        Czech,
        Danish,
        Dutch,
        English,
        EnglishUK,
        EnglishUS,
        Estonian,
        Filipino,
        Finnish,
        French,
        German,
        Greek,
        Gujarati,
        Hausa,
        Hebrew,
        Hindi,
        Hungarian,
        Indonesian,
        Irish,
        Italian,
        Japanese,
        Kannada,
        Kazakh,
        Korean,
        Lao,
        Latvian,
        Lithuanian,
        Macedonian,
        Malay,
        Malayalam,
        Marathi,
        Norwegian,
        Persian,
        Polish,
        PortugueseBrazil,
        PortuguesePortugal,
        Punjabi,
        Romanian,
        Russian,
        Serbian,
        Slovak,
        Slovenian,
        Spanish,
        SpanishArgentina,
        SpanishSpain,
        SpanishMexico,
        Swahili,
        Swedish,
        Tamil,
        Telugu,
        Thai,
        Turkish,
        Ukrainian,
        Urdu,
        Uzbek,
        Vietnamese,
        Zulu,
    }

    impl ToString for LanguageCode {
        fn to_string(&self) -> String {
            match self {
                LanguageCode::Afrikaans => "af".to_string(),
                LanguageCode::Albanian => "sq".to_string(),
                LanguageCode::Arabic => "ar".to_string(),
                LanguageCode::Azerbaijani => "az".to_string(),
                LanguageCode::Bengali => "bn".to_string(),
                LanguageCode::Bulgarian => "bg".to_string(),
                LanguageCode::Catalan => "ca".to_string(),
                LanguageCode::ChineseChina => "zh_CN".to_string(),
                LanguageCode::ChineseHongKong => "zh_HK".to_string(),
                LanguageCode::ChineseTaiwan => "zh_TW".to_string(),
                LanguageCode::Croatian => "hr".to_string(),
                LanguageCode::Czech => "cs".to_string(),
                LanguageCode::Danish => "da".to_string(),
                LanguageCode::Dutch => "nl".to_string(),
                LanguageCode::English => "en".to_string(),
                LanguageCode::EnglishUK => "en_GB".to_string(),
                LanguageCode::EnglishUS => "en_US".to_string(),
                LanguageCode::Estonian => "et".to_string(),
                LanguageCode::Filipino => "fil".to_string(),
                LanguageCode::Finnish => "fi".to_string(),
                LanguageCode::French => "fr".to_string(),
                LanguageCode::German => "de".to_string(),
                LanguageCode::Greek => "el".to_string(),
                LanguageCode::Gujarati => "gu".to_string(),
                LanguageCode::Hausa => "ha".to_string(),
                LanguageCode::Hebrew => "he".to_string(),
                LanguageCode::Hindi => "hi".to_string(),
                LanguageCode::Hungarian => "hu".to_string(),
                LanguageCode::Indonesian => "id".to_string(),
                LanguageCode::Irish => "ga".to_string(),
                LanguageCode::Italian => "it".to_string(),
                LanguageCode::Japanese => "ja".to_string(),
                LanguageCode::Kannada => "kn".to_string(),
                LanguageCode::Kazakh => "kk".to_string(),
                LanguageCode::Korean => "ko".to_string(),
                LanguageCode::Lao => "lo".to_string(),
                LanguageCode::Latvian => "lv".to_string(),
                LanguageCode::Lithuanian => "lt".to_string(),
                LanguageCode::Macedonian => "mk".to_string(),
                LanguageCode::Malay => "ms".to_string(),
                LanguageCode::Malayalam => "ml".to_string(),
                LanguageCode::Marathi => "mr".to_string(),
                LanguageCode::Norwegian => "nb".to_string(),
                LanguageCode::Persian => "fa".to_string(),
                LanguageCode::Polish => "pl".to_string(),
                LanguageCode::PortugueseBrazil => "pt_BR".to_string(),
                LanguageCode::PortuguesePortugal => "pt_PT".to_string(),
                LanguageCode::Punjabi => "pa".to_string(),
                LanguageCode::Romanian => "ro".to_string(),
                LanguageCode::Russian => "ru".to_string(),
                LanguageCode::Serbian => "sr".to_string(),
                LanguageCode::Slovak => "sk".to_string(),
                LanguageCode::Slovenian => "sl".to_string(),
                LanguageCode::Spanish => "es".to_string(),
                LanguageCode::SpanishArgentina => "es_AR".to_string(),
                LanguageCode::SpanishSpain => "es_ES".to_string(),
                LanguageCode::SpanishMexico => "es_MX".to_string(),
                LanguageCode::Swahili => "sw".to_string(),
                LanguageCode::Swedish => "sv".to_string(),
                LanguageCode::Tamil => "ta".to_string(),
                LanguageCode::Telugu => "te".to_string(),
                LanguageCode::Thai => "th".to_string(),
                LanguageCode::Turkish => "tr".to_string(),
                LanguageCode::Ukrainian => "uk".to_string(),
                LanguageCode::Urdu => "ur".to_string(),
                LanguageCode::Uzbek => "uz".to_string(),
                LanguageCode::Vietnamese => "vi".to_string(),
                LanguageCode::Zulu => "zu".to_string(),
            }
        }
    }
}
